// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWCJyJtfYjIt6XHyLapZW2DiWYKH6xDM',
    appId: '1:124923317053:web:6c10f8ab9fd0ef41a8d354',
    messagingSenderId: '124923317053',
    projectId: 'dtpl-1076c',
    authDomain: 'dtpl-1076c.firebaseapp.com',
    storageBucket: 'dtpl-1076c.appspot.com',
    measurementId: 'G-HR2W7RZMR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KVIiPN40iN_uNsDg9hbSWGEP-OA-ZHk',
    appId: '1:124923317053:android:ac5cf7fee17cae12a8d354',
    messagingSenderId: '124923317053',
    projectId: 'dtpl-1076c',
    storageBucket: 'dtpl-1076c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxIKjLoCwwdyZRUrSHF9EuPYeHNYF624w',
    appId: '1:124923317053:ios:ef0cbb8f65da0576a8d354',
    messagingSenderId: '124923317053',
    projectId: 'dtpl-1076c',
    storageBucket: 'dtpl-1076c.appspot.com',
    iosBundleId: 'com.example.dtplApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxIKjLoCwwdyZRUrSHF9EuPYeHNYF624w',
    appId: '1:124923317053:ios:dc531e009e7fc398a8d354',
    messagingSenderId: '124923317053',
    projectId: 'dtpl-1076c',
    storageBucket: 'dtpl-1076c.appspot.com',
    iosBundleId: 'com.example.dtplApp.RunnerTests',
  );
}
